config/urls.py
"""
URL configuration for config project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function vis
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
   dd a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
]

users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from .apps import UsersConfig
from .views import RegisterView, ProfileView, MyLogoutView, MyLoginView, email_verification, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),
    path('reset_password/', reset_password, name='reset_password'),
    path('profile/', ProfileView.as_view(template_name='users/profile.html'), name='profile'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(
        verbose_name='почта',
        unique=True
    )
    phone = models.CharField(max_length=55, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.CharField(max_length=55, verbose_name='страна', **NULLABLE)
    token = models.CharField(max_length=100, verbose_name='токен', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        # Строковое отображение объекта
        return self.email

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from users.models import User


class RegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('email', 'phone', 'avatar', 'country')


class UserAuthenticationForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ('email', 'password')

users/views.py
import random
import secrets
import string

from django.conf.global_settings import EMAIL_HOST_USER
from django.contrib.auth import logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView, LoginView
from django.core.mail import send_mail
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView
from users.forms import RegisterForm, UserProfileForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = RegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http:/{host}/users/email-confirm/{token}/'
        send_mail(subject="Подтвердите почту",
                  message=f"Чтобы подтвердить почту, перейдите по ссылке {url}",
                  from_email=EMAIL_HOST_USER,
                  recipient_list=[user.email, ]
                  )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


def reset_password(request):
    context = {
        'success_message': 'Новый пароль выслан на вашу почту.',
    }
    if request.method == 'POST':
        email = request.POST.get('email')
        user = get_object_or_404(User, email=email)
        characters = string.ascii_letters + string.digits
        characters_list = list(characters)
        random.shuffle(characters_list)
        password = ''.join(characters_list[:10])
        user.set_password(password)
        user.save()

        send_mail(
            subject='Смена пароля',
            message=f'Ваш новый пароль: {password}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return render(request, 'users/reset_password.html', context)
    return render(request, 'users/reset_password.html')






class ProfileView(LoginRequiredMixin, UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user


class MyLogoutView(LogoutView):
    model = User
    form_class = RegisterForm
    template_name = 'users/login.html'
    success_url = reverse_lazy('catalog:product_list')

    def logout_view(request):
        logout(request)
        return redirect("/")


class MyLoginView(LoginView):
    model = User
    form_class = AuthenticationForm
    template_name = 'users/login.html'
    success_url = reverse_lazy('catalog:product_list')

users/templates/users/login.html
{% extends 'base.html' %}
{% block content %}

    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-primary" value="Войти">
                     <a href="{% url 'users:reset_password' %}" type="submit" class="btn btn-warning">
                        Восстановить пароль
                    </a>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/logout.html
{% extends 'base.html' %}
{% block content %}

<form method="post"> <!-- action="{% url 'logout' %}"> -->
    <!-- {% csrf_token %} -->
    <button type="submit">Logout</button>
</form>

{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
   <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-primary" value="Сохранить">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'base.html' %}
{% block content %}

    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="POST">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="submit" class="btn btn-primary" value="Сохранить">
                </form>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/reset_password.html
{% extends 'base.html' %}

{% block content %}
<div class="col-12">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">
                    Восстановление пароля
                </h3>
            </div>
            <div class="card-body">
                {% if success_message %}
                <p>{{ success_message }}</p>
                <a href="{% url 'users:login' %}" class="btn btn-success">Войти в личный кабинет</a>
                {% else %}
                <form class="row" method="post">
                    {% csrf_token %}
                    <input type="email" name="email">
                    <button type="submit" class="btn btn-success">
                        Восстановить пароль
                    </button>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}