catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from .views import ContactsTemplateView, ProductListView, ProductDetailView, ProductCreateView, ProductDeleteView, \
    ProductUpdateView, CategoriesListView

app_name = 'catalog'

urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
    path('categories/', CategoriesListView.as_view(), name='categories_list'),
    path('detail/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('product_update/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('product_delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),
    path('create/', ProductCreateView.as_view(), name='create'),
]

config/urls.py
"""
URL configuration for config project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function vis
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
   dd a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users'))
]

users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path

from .apps import UsersConfig
from .views import RegisterView, ProfileView, MyLogoutView, MyLoginView, email_verification, reset_password

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('register/', RegisterView.as_view(template_name='users/register.html'), name='register'),
    path('reset_password/', reset_password, name='reset_password'),
    path('profile/', ProfileView.as_view(template_name='users/profile.html'), name='profile'),
    path('email-confirm/<str:token>/', email_verification, name='email_confirm'),
]

catalog/models.py
from django.db import models

from users.models import User

NULLABLE = {'blank': True, 'null': True}


class Product(models.Model):
    name_product = models.CharField(max_length=20, verbose_name='имя')
    description = models.CharField(max_length=150, verbose_name='описание', **NULLABLE)
    preview = models.ImageField(upload_to='product/', verbose_name='изображение', **NULLABLE)
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, **NULLABLE)
    price = models.IntegerField(verbose_name='цена', **NULLABLE)
    made = models.DateField(verbose_name='изготовлено', auto_now_add=True)
    change = models.DateField(verbose_name='изменено', auto_now=True)
    owner = models.ForeignKey(User, verbose_name='Владелец', blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        # Строковое отображение объекта
        return f'{self.pk} {self.name_product} {self.price} {self.category}'

    class Meta:
        verbose_name = 'продукт'
        verbose_name_plural = 'продукты'
        permissions = [
            ("can_edit_category", "Can edit category"),
            ("can_edit_description", "Can edit description"),
        ]


class Category(models.Model):
    name_category = models.CharField(max_length=20, verbose_name='имя')
    description = models.CharField(max_length=150, verbose_name='описание')

    def __str__(self):
        return f'{self.pk} {self.name_category}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

catalog/forms.py
from django import forms
from catalog.models import Product


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'


class ProductModerForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ("description", "category")

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.views import generic
from catalog.models import Product, Category
from django.forms import inlineformset_factory
from django.urls import reverse_lazy, reverse
from catalog.forms import ProductForm, ProductModerForm
from catalog.services import get_category_from_cache


class ContactsTemplateView(generic.TemplateView):
    template_name = 'catalog/contacts.html'


class ProductListView(generic.ListView):
    model = Product
    template_name = 'catalog/product_list.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Список товаров'
        return context_data


class ProductDetailView(generic.DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = context_data['object']
        return context_data


class ProductCreateView(LoginRequiredMixin, generic.CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product_list')
    extra_context = {
        'title': 'Создание продукта'
    }

    def form_valid(self, form):
        product = form.save()
        user = self.request.user
        product.owner = user
        product.save()
        return super().form_valid(form)


class ProductDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product_list')


class ProductUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Product
    form_class = ProductForm
    extra_context = {
        'title': 'Изменение продукта'
    }
    success_url = reverse_lazy('catalog:product_list')

    def get_form_class(self):
        user = self.request.user
        if user == self.object.owner:
            return ProductForm
        if user.has_perm("catalog.can_edit_description") and user.has_perm("catalog.can_edit_category"):
            return ProductModerForm
        raise PermissionDenied


class CategoriesListView(generic.ListView):
    model = Category
    template_name = 'catalog/categories_list.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        context_data['title'] = 'Список категорий'
        return context_data

    def get_queryset(self):
        return get_category_from_cache()

catalog/templates/Catalog/categories_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name_category }}</h4>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

catalog/templates/Catalog/contacts.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                    </form>
                    <input type="submit">
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

catalog/templates/Catalog/product_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<div class="col-6" xmlns="http://www.w3.org/1999/html">
    <div class="card">
        <div class="card-header"></div>
        <div class="card-body">
          <form method="POST">
            {% csrf_token %}
            {{ object }}
            <button type="submit" class="btn btn-primary">Удалить</button>
          </form>
          <a class="btn btn-primary" href="{% url 'catalog:product_list' %}">Назад</a>
        </div>
    </div>
</div>


{% endblock %}

catalog/templates/Catalog/product_detail.html
{% extends 'base.html' %}
{% block content %}
  <div class="row text-center">
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name_product }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.price }} руб.</h1>
                    <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                        <li>- {{ object.description }}</li>
                        <li>- {{ object.category }}</li>
                        <li>- {{ object.made }}</li>
                        <li>- {{ object.change }}</li>
                        <p class="card-text">Категория: {{ object.category }}</p>
                    </ul>
                    <button type="button" class="btn btn-lg btn-block btn-outline-primary">Купить</button>
                </div>
            </div>
        </div>
      <img src="/media/{{ object.preview }}" />
  </div>
{% endblock %}

catalog/templates/Catalog/product_form.html
{% extends 'base.html' %}
{% block content %}

<form class="row" method="POST">
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Сохранить</button>
            </div>
        </div>
    </div>
</form>

{% endblock %}

catalog/templates/Catalog/product_list.html
{% extends 'base.html' %}
{% block content %}
<a href="{% url 'catalog:create' %}" class ="btn btn-primary">Создать продукт</a>
<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">{{ object.name_product }}</h4>
                </div>
                <div class="card-body">
                    <h1 class="card-title pricing-card-title">{{ object.price }} руб.</h1>
                    {% for version in object.version.all %}
                        <p class="card-text">{% if version.is_active %}Активная версия: {{ version }} {% endif %}</p>
                    {% endfor %}
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_detail' object.pk %}">Подробнее</a>
                    {% if perms.catalog.can_edit_description and perms.catalog.can_edit_category or user == product.owner %}
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_update' object.pk %}">Изменить </a>
                    <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_delete' object.pk %}">Удалить</a>
                    {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endblock %}
</div>
<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>